python fit_Proto_Arky 0 1
python fit_Proto_Arky 0 2
python fit_Proto_Arky 0 3
python fit_Proto_Arky 0 4
python fit_Proto_Arky 0 5
python fit_Proto_Arky 0 6
python fit_Proto_Arky 0 7
python fit_Proto_Arky 0 8
python fit_Proto_Arky 0 9
python fit_Proto_Arky 0 10
python fit_Proto_Arky 1 1
python fit_Proto_Arky 1 2
python fit_Proto_Arky 1 3
python fit_Proto_Arky 1 4
python fit_Proto_Arky 1 5
python fit_Proto_Arky 1 6
python fit_Proto_Arky 1 7
python fit_Proto_Arky 1 8
python fit_Proto_Arky 1 9
python fit_Proto_Arky 1 10