python fit_Proto_Arky.py 0 11 &
python fit_Proto_Arky.py 0 12 &
python fit_Proto_Arky.py 0 13 &
python fit_Proto_Arky.py 0 14 &
python fit_Proto_Arky.py 0 15 &
python fit_Proto_Arky.py 0 16 &
python fit_Proto_Arky.py 0 17 &
python fit_Proto_Arky.py 0 18 &
python fit_Proto_Arky.py 0 19 &
python fit_Proto_Arky.py 0 20 &
python fit_Proto_Arky.py 1 11 &
python fit_Proto_Arky.py 1 12 &
python fit_Proto_Arky.py 1 13 &
python fit_Proto_Arky.py 1 14 &
python fit_Proto_Arky.py 1 15 &
python fit_Proto_Arky.py 1 16 &
python fit_Proto_Arky.py 1 17 &
python fit_Proto_Arky.py 1 18 &
python fit_Proto_Arky.py 1 19 &
python fit_Proto_Arky.py 1 20
