python fit_Proto_Arky.py 0 1 &
python fit_Proto_Arky.py 0 2 &
python fit_Proto_Arky.py 0 3 &
python fit_Proto_Arky.py 0 4 &
python fit_Proto_Arky.py 0 5 &
python fit_Proto_Arky.py 0 6 &
python fit_Proto_Arky.py 0 7 &
python fit_Proto_Arky.py 0 8 &
python fit_Proto_Arky.py 0 9 &
python fit_Proto_Arky.py 0 10 &
python fit_Proto_Arky.py 0 11 &
python fit_Proto_Arky.py 0 12 &
python fit_Proto_Arky.py 1 1 &
python fit_Proto_Arky.py 1 2 &
python fit_Proto_Arky.py 1 3 &
python fit_Proto_Arky.py 1 4 &
python fit_Proto_Arky.py 1 5 &
python fit_Proto_Arky.py 1 6 &
python fit_Proto_Arky.py 1 7 &
python fit_Proto_Arky.py 1 8 &
python fit_Proto_Arky.py 1 9 &
python fit_Proto_Arky.py 1 10 &
python fit_Proto_Arky.py 1 11 &
python fit_Proto_Arky.py 1 12
